// SAMPLE CONTENT: fictional events so the booking flow can be demoed end to end.
// Flagged is_sample and badged "Sample" in the UI. Dates are offsets from the
// day you run the seed.
const PHOTOS = {
  laptopsTeam: 'photo-1531482615713-2afd69097998',
  openOffice: 'photo-1504384308090-c894fdcc538d',
  workshopRoom: 'photo-1556761175-b413da4baf72',
  highFive: 'photo-1600880292203-757bb62b4baf',
  friends: 'photo-1529156069898-49953e39b3ac',
  conference: 'photo-1540575467063-178a50c2df87',
  speaker: 'photo-1475721027785-f74eccf877e2',
  meeting: 'photo-1552664730-d307ca884978',
  planning: 'photo-1528605248644-14dd04022da1',
  codeLaptop: 'photo-1517694712202-14dd9538aa97',
  codeScreen: 'photo-1555066931-4365d14bab8c',
  codeDark: 'photo-1461749280684-dccba630e2f6',
  codeMac: 'photo-1587620962725-abab7fe55159',
  techTeam: 'photo-1519389950473-47ba0277781c',
}
export const unsplash = (id, w = 800, h = 480) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&h=${h}&q=70`

export const DEMO_EVENTS = [
  {
    id: 'cf-101',
    offset: 6,
    title: 'Build with Gemini: Agents Hack Night',
    type: 'Hackathon',
    category: 'hackathon',
    mode: 'In-person',
    city: 'Bengaluru',
    venue: 'Koramangala Innovation Hub, 5th Block',
    time: '18:00',
    endTime: '06:00',
    organizerChapter: 'GDG Bengaluru',
    capacity: 500,
    booked: 125,
    image: PHOTOS.laptopsTeam,
    tags: ['Gemini', 'Agents', 'Overnight'],
    description:
      'A 12-hour overnight sprint to build AI agents with the Gemini API. Form teams of up to four, pick a track (productivity, civic tech or developer tooling), and demo to a panel of community mentors at sunrise.',
    requirements: ['Laptop with charger', 'Google account for AI Studio', 'Basic Python or JavaScript'],
    learn: ['Function calling with Gemini', 'Designing multi-step agent workflows', 'Shipping a demo in 12 hours'],
  },
  {
    id: 'cf-102',
    offset: 3,
    title: 'Flutter Forward: Hands-on Workshop',
    type: 'Event',
    category: 'workshop',
    mode: 'In-person',
    city: 'Delhi',
    venue: 'IIIT Delhi, Seminar Block B',
    time: '10:00',
    endTime: '16:00',
    organizerChapter: 'GDG New Delhi',
    capacity: 120,
    booked: 97,
    image: PHOTOS.workshopRoom,
    tags: ['Flutter', 'Dart', 'Mobile'],
    description:
      'Go from zero to a working cross-platform app in one day. We cover widgets, state management with Riverpod, and deploying to Android and the web.',
    requirements: ['Flutter SDK installed', 'Android Studio or VS Code', 'An Android device or emulator'],
    learn: ['Flutter widget tree fundamentals', 'State management with Riverpod', 'Deploying Flutter to the web'],
  },
  {
    id: 'cf-103',
    offset: 9,
    title: 'Cloud Study Jam: Kubernetes on GKE',
    type: 'Event',
    category: 'workshop',
    mode: 'Online',
    city: 'Hyderabad',
    venue: 'Google Meet (link shared after booking)',
    time: '19:00',
    endTime: '21:00',
    organizerChapter: 'GDG Hyderabad',
    capacity: 300,
    booked: 188,
    image: PHOTOS.codeScreen,
    tags: ['Kubernetes', 'GKE', 'Cloud'],
    description:
      'A guided lab where you deploy, scale and observe a microservice app on Google Kubernetes Engine. Mentors are on hand in breakout rooms.',
    requirements: ['Stable internet connection', 'Google Cloud Skills Boost account'],
    learn: ['Pods, deployments and services', 'Autoscaling on GKE', 'Observability with Cloud Logging'],
  },
  {
    id: 'cf-104',
    offset: 14,
    title: 'DevFest Pune 2026 (Sample)',
    type: 'Event',
    category: 'gdg',
    mode: 'In-person',
    city: 'Pune',
    venue: 'COEP Auditorium, Shivajinagar',
    time: '09:00',
    endTime: '18:00',
    organizerChapter: 'GDG Pune',
    capacity: 800,
    booked: 612,
    image: PHOTOS.conference,
    tags: ['DevFest', 'AI', 'Web', 'Android'],
    description:
      'A full-day community conference with three parallel tracks (AI, Web and Android), a startup alley, and lightning talks from first-time speakers.',
    requirements: ['Valid college or company ID at entry'],
    learn: ["What's new across Google developer tools", 'Real-world case studies from Pune startups', 'How to give your first tech talk'],
  },
  {
    id: 'cf-105',
    offset: 2,
    title: 'Firebase & Web Meetup',
    type: 'Event',
    category: 'gdg',
    mode: 'In-person',
    city: 'Mumbai',
    venue: 'WeWork BKC, Bandra Kurla Complex',
    time: '18:30',
    endTime: '21:00',
    organizerChapter: 'GDG Mumbai',
    capacity: 80,
    booked: 80,
    image: PHOTOS.meeting,
    tags: ['Firebase', 'Web', 'Meetup'],
    description:
      'An evening of short talks on Firebase Auth, Firestore data modelling and Hosting, followed by open networking and chai.',
    requirements: ['None, just bring your curiosity'],
    learn: ['Firestore data modelling patterns', 'Securing apps with Firebase Auth', 'Meeting Mumbai web developers'],
  },
  {
    id: 'cf-106',
    offset: 20,
    title: 'Hack for Chennai: Civic Tech Hackathon',
    type: 'Hackathon',
    category: 'hackathon',
    mode: 'In-person',
    city: 'Chennai',
    venue: 'IIT Madras Research Park, Taramani',
    time: '09:00',
    endTime: '09:00',
    organizerChapter: 'GDG Chennai',
    capacity: 250,
    booked: 164,
    image: PHOTOS.highFive,
    tags: ['Civic Tech', '24 hours', 'Open Data'],
    description:
      'A 24-hour hackathon using open city datasets on transport, water and waste. The best projects get mentoring to pilot with local civic groups.',
    requirements: ['Team of 2–4', 'Laptop', 'Student or professional ID'],
    learn: ['Working with open government data', 'Rapid prototyping', 'Pitching to non-technical judges'],
  },
  {
    id: 'cf-107',
    offset: 5,
    title: 'Android Study Group: Jetpack Compose',
    type: 'Event',
    category: 'workshop',
    mode: 'Online',
    city: 'Kolkata',
    venue: 'YouTube Live + Discord',
    time: '20:00',
    endTime: '21:30',
    organizerChapter: 'GDG Kolkata',
    capacity: 400,
    booked: 141,
    image: PHOTOS.codeMac,
    tags: ['Android', 'Compose', 'Kotlin'],
    description:
      'Week 3 of our Compose study group: layouts, theming and animations. Code along live, then share your build in Discord for feedback.',
    requirements: ['Android Studio (latest stable)', 'Basic Kotlin'],
    learn: ['Compose layouts and modifiers', 'Material 3 theming', 'Animations in Compose'],
  },
  {
    id: 'cf-108',
    offset: 11,
    title: 'Women Techmakers Bengaluru Meetup',
    type: 'Event',
    category: 'gdg',
    mode: 'In-person',
    city: 'Bengaluru',
    venue: 'Indiranagar Community Hall, 100 Feet Road',
    time: '11:00',
    endTime: '15:00',
    organizerChapter: 'GDG Bengaluru',
    capacity: 150,
    booked: 103,
    image: PHOTOS.friends,
    tags: ['WTM', 'Community', 'Careers'],
    description:
      'Panels and roundtables on career growth, open source and leadership in tech, open to everyone who supports women in technology.',
    requirements: ['Registration confirmation on your phone'],
    learn: ['Career paths in developer relations', 'Getting started with open source', 'Building your tech network'],
  },
  {
    id: 'cf-109',
    offset: 26,
    title: 'Delhi Web3 × AI Buildathon',
    type: 'Hackathon',
    category: 'hackathon',
    mode: 'Online',
    city: 'Delhi',
    venue: 'Online (Discord + Devpost-style submission)',
    time: '10:00',
    endTime: '10:00',
    organizerChapter: 'GDG New Delhi',
    capacity: 1000,
    booked: 356,
    image: PHOTOS.codeDark,
    tags: ['AI', 'Web3', '48 hours'],
    description:
      'A 48-hour remote buildathon exploring where AI meets decentralised apps. Async-friendly, with mentor office hours every six hours.',
    requirements: ['GitHub account', 'Team of 1–4'],
    learn: ['Integrating LLMs into dApps', 'Async team collaboration', 'Writing a strong project README'],
  },
  {
    id: 'cf-110',
    offset: 8,
    title: 'ML Paper Reading Circle: Transformers 101',
    type: 'Event',
    category: 'gdg',
    mode: 'In-person',
    city: 'Hyderabad',
    venue: 'T-Hub, Raidurg',
    time: '17:00',
    endTime: '19:00',
    organizerChapter: 'GDG Hyderabad',
    capacity: 60,
    booked: 41,
    image: PHOTOS.planning,
    tags: ['ML', 'Research', 'Discussion'],
    description:
      'A relaxed, discussion-first session walking through "Attention Is All You Need" with visual intuitions and a small PyTorch demo.',
    requirements: ['Skim the paper beforehand (optional)'],
    learn: ['How attention works, intuitively', 'Reading ML papers efficiently', 'A tiny transformer in PyTorch'],
  },
  {
    id: 'cf-111',
    offset: 17,
    title: 'Pune Campus Hackathon: Build for Bharat',
    type: 'Hackathon',
    category: 'hackathon',
    mode: 'In-person',
    city: 'Pune',
    venue: 'MIT-WPU Campus, Kothrud',
    time: '08:30',
    endTime: '20:00',
    organizerChapter: 'GDG Pune',
    capacity: 300,
    booked: 298,
    image: PHOTOS.techTeam,
    tags: ['Students', 'Bharat', 'Social Impact'],
    description:
      'A student-first hackathon for solutions built for the next billion users: vernacular interfaces, low-bandwidth apps and agri-tech.',
    requirements: ['Student ID', 'Team of 3–4', 'Laptop'],
    learn: ['Designing for low-bandwidth users', 'Multilingual UI with Gemini', 'Demo-day storytelling'],
  },
  {
    id: 'cf-112',
    offset: 4,
    title: 'Mumbai Cloud Run Workshop',
    type: 'Event',
    category: 'workshop',
    mode: 'In-person',
    city: 'Mumbai',
    venue: 'Powai Tech Park, Hiranandani',
    time: '14:00',
    endTime: '18:00',
    organizerChapter: 'GDG Mumbai',
    capacity: 90,
    booked: 52,
    image: PHOTOS.codeLaptop,
    tags: ['Cloud Run', 'Serverless', 'Docker'],
    description:
      'Containerise a web app and ship it to Cloud Run. Covers CI/CD with Cloud Build, custom domains, and keeping costs near zero.',
    requirements: ['Laptop with Docker', 'Google Cloud account (free credits provided)'],
    learn: ['Containerising apps', 'Serverless deploys on Cloud Run', 'CI/CD with Cloud Build'],
  },
  {
    id: 'cf-113',
    offset: 12,
    title: 'Chennai Kotlin Roadshow',
    type: 'Event',
    category: 'gdg',
    mode: 'In-person',
    city: 'Chennai',
    venue: 'Anna University Alumni Centre, Guindy',
    time: '10:00',
    endTime: '17:00',
    organizerChapter: 'GDG Chennai',
    capacity: 200,
    booked: 120,
    image: PHOTOS.speaker,
    tags: ['Kotlin', 'KMP', 'Talks'],
    description:
      'A day of talks on Kotlin Multiplatform, coroutines and server-side Kotlin, plus a "bring your bug" clinic with community experts.',
    requirements: ['None'],
    learn: ['Kotlin Multiplatform in production', 'Structured concurrency with coroutines', 'Server-side Kotlin with Ktor'],
  },
  {
    id: 'cf-114',
    offset: 30,
    title: 'Kolkata Open Source Sprint',
    type: 'Hackathon',
    category: 'hackathon',
    mode: 'In-person',
    city: 'Kolkata',
    venue: 'Salt Lake Sector V, Webel Bhavan',
    time: '10:00',
    endTime: '18:00',
    organizerChapter: 'GDG Kolkata',
    capacity: 150,
    booked: 37,
    image: PHOTOS.openOffice,
    tags: ['Open Source', 'Hacktoberfest', 'Beginner friendly'],
    description:
      'Pair with maintainers to land your first open-source pull requests. Good-first-issues are curated in advance across 20+ repositories.',
    requirements: ['GitHub account', 'Git installed'],
    learn: ['Navigating unfamiliar codebases', 'Writing a great pull request', 'Open-source etiquette'],
  },
  // Past events: only used for attendee history ("Hackathons attended").
  {
    id: 'cf-090',
    offset: -40,
    title: 'Monsoon Hack Bengaluru',
    type: 'Hackathon',
    category: 'hackathon',
    mode: 'In-person',
    city: 'Bengaluru',
    venue: 'HSR Layout Makerspace',
    time: '09:00',
    endTime: '21:00',
    organizerChapter: 'GDG Bengaluru',
    capacity: 200,
    booked: 200,
    image: PHOTOS.laptopsTeam,
    tags: ['Past'],
    description: 'A past sample hackathon, kept for booking history.',
    requirements: [],
    learn: [],
  },
  {
    id: 'cf-091',
    offset: -75,
    title: 'Solution Challenge Kickoff Hack',
    type: 'Hackathon',
    category: 'hackathon',
    mode: 'Online',
    city: 'Delhi',
    venue: 'Online',
    time: '10:00',
    endTime: '18:00',
    organizerChapter: 'GDG New Delhi',
    capacity: 500,
    booked: 420,
    image: PHOTOS.codeDark,
    tags: ['Past'],
    description: 'A past sample hackathon, kept for booking history.',
    requirements: [],
    learn: [],
  },
]


export const SAMPLE_ATTENDEES = [
  ['Aarav Mehta', 'aarav.m@example.com'],
  ['Diya Iyer', 'diya.i@example.com'],
  ['Kabir Singh', 'kabir.s@example.com'],
  ['Meera Pillai', 'meera.p@example.com'],
  ['Rohan Das', 'rohan.d@example.com'],
  ['Ananya Kulkarni', 'ananya.k@example.com'],
  ['Ishaan Reddy', 'ishaan.r@example.com'],
  ['Sneha Banerjee', 'sneha.b@example.com'],
  ['Vikram Joshi', 'vikram.j@example.com'],
  ['Tara Menon', 'tara.m@example.com'],
]
